# this file configures the analyzer, which statically analyzes dart code to
# check for errors, warnings, and lints.
#
# the issues identified by the analyzer are surfaced in the ui of dart-enabled
# ides (https://dart.dev/tools#ides-and-editors). the analyzer can also be
# invoked from the command line by running flutter analyze.

# the following line activates a set of recommended lints for flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  # the lint rules applied to this project can be customized in the
  # section below to disable rules from the package:flutterlints/flutter.yaml
  # included above or to enable additional rules. a list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the // ignore: nameoflint and
  # // ignoreforfile: nameoflint syntax on the line or in the file
  # producing the lint.
  rules:
    # avoidprint: false # uncomment to disable the avoidprint rule
    # prefersinglequotes: true # uncomment to enable the prefersinglequotes rule

# additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
