name: mobile_frontend
description: "A new Flutter project."
# the following line prevents the package from being accidentally published to
# pub.dev using flutter pub publish. this is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# the following defines the version and build number for your application.
# a version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# in android, build-name is used as versionname while build-number used as versioncode.
# read more about android versioning at https://developer.android.com/studio/publish/versioning
# in ios, build-name is used as cfbundleshortversionstring while build-number is used as cfbundleversion.
# read more about ios versioning at
# https://developer.apple.com/library/archive/documentation/general/reference/infoplistkeyreference/articles/corefoundationkeys.html
# in windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.0

# dependencies specify other packages that your package needs in order to work.
# to automatically upgrade your package dependencies to the latest versions
# consider running flutter pub upgrade --major-versions. alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. to see which dependencies have newer
# versions available, run flutter pub outdated.
dependencies:
  flutter:
    sdk: flutter
    # firebase core - required for any firebase usage
  firebase_core: ^3.3.0

  # authentication
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1

  # cloud firestore (nosql database)
  cloud_firestore: ^5.1.0


  # the following adds the cupertino icons font to your application.
  # use with the cupertinoicons class for ios style icons.
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.2.1
  file_picker: ^10.3.9
  provider: ^6.1.1
  fl_chart: ^0.68.0
  firebase_storage: ^12.4.10
  http: ^1.6.0
  youtube_player_iframe: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  fake_cloud_firestore: any
  firebase_auth_mocks: any

  # the "flutterlints" package below contains a set of recommended lints to
  # encourage good coding practices. the lint set provided by the package is
  # activated in the analysisoptions.yaml file located at the root of your
  # package. see that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# for information on the generic dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# the following section is specific to flutter packages.
flutter:

  # the following line ensures that the material icons font is
  # included with your application, so that you can use the icons in
  # the material icons class.
  uses-material-design: true

  # to add assets to your application, add an assets section, like this:
  # assets:
  # - images/adotburr.jpeg
  # - images/adotham.jpeg

  # an image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # for details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # to add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. for
  # example:
  # fonts:
  # - family: schyler
  # fonts:
  # - asset: fonts/schyler-regular.ttf
  # - asset: fonts/schyler-italic.ttf
  # style: italic
  # - family: trajan pro
  # fonts:
  # - asset: fonts/trajanpro.ttf
  # - asset: fonts/trajanprobold.ttf
  # weight: 700
  #
  # for details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
