// file generated by antigravity ai but based on your project configuration.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// default [firebaseoptions] for use with your firebase apps.
///
/// example:
/// dart
/// import 'firebaseoptions.dart';
/// // ...
/// await firebase.initializeapp(
/// options: defaultfirebaseoptions.currentplatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqTtXV6wbh6GWCsLCac0EEm7Crf2WqGyg',
    appId: 'YOUR_WEB_APP_ID', // todo: replace with your web app id from firebase console
    messagingSenderId: '976583278348',
    projectId: 'fitbiteapp-a1940',
    authDomain: 'fitbiteapp-a1940.firebaseapp.com',
    storageBucket: 'fitbiteapp-a1940.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqTtXV6wbh6GWCsLCac0EEm7Crf2WqGyg',
    appId: '1:976583278348:android:d6d731fc23ab2b55dcd329',
    messagingSenderId: '976583278348',
    projectId: 'fitbiteapp-a1940',
    storageBucket: 'fitbiteapp-a1940.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqTtXV6wbh6GWCsLCac0EEm7Crf2WqGyg',
    appId: 'YOUR_IOS_APP_ID', // todo: add ios app id if needed
    messagingSenderId: '976583278348',
    projectId: 'fitbiteapp-a1940',
    storageBucket: 'fitbiteapp-a1940.firebasestorage.app',
    iosBundleId: 'com.example.mobileFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqTtXV6wbh6GWCsLCac0EEm7Crf2WqGyg',
    appId: 'YOUR_MACOS_APP_ID', // todo: add macos app id if needed
    messagingSenderId: '976583278348',
    projectId: 'fitbiteapp-a1940',
    storageBucket: 'fitbiteapp-a1940.firebasestorage.app',
    iosBundleId: 'com.example.mobileFrontend',
  );
}
