// File generated by Antigravity ai but based on your project configuration.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqTtXV6wbh6GWCsLCac0EEm7Crf2WqGyg',
    appId: 'YOUR_WEB_APP_ID', // TODO: Replace with your Web App ID from Firebase Console
    messagingSenderId: '976583278348',
    projectId: 'fitbiteapp-a1940',
    authDomain: 'fitbiteapp-a1940.firebaseapp.com',
    storageBucket: 'fitbiteapp-a1940.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqTtXV6wbh6GWCsLCac0EEm7Crf2WqGyg',
    appId: '1:976583278348:android:d6d731fc23ab2b55dcd329',
    messagingSenderId: '976583278348',
    projectId: 'fitbiteapp-a1940',
    storageBucket: 'fitbiteapp-a1940.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqTtXV6wbh6GWCsLCac0EEm7Crf2WqGyg',
    appId: 'YOUR_IOS_APP_ID', // TODO: Add iOS App ID if needed
    messagingSenderId: '976583278348',
    projectId: 'fitbiteapp-a1940',
    storageBucket: 'fitbiteapp-a1940.firebasestorage.app',
    iosBundleId: 'com.example.mobileFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqTtXV6wbh6GWCsLCac0EEm7Crf2WqGyg',
    appId: 'YOUR_MACOS_APP_ID', // TODO: Add macOS App ID if needed
    messagingSenderId: '976583278348',
    projectId: 'fitbiteapp-a1940',
    storageBucket: 'fitbiteapp-a1940.firebasestorage.app',
    iosBundleId: 'com.example.mobileFrontend',
  );
}
